services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    restart: always
    env_file:
      - path: ./apps/backend/.env
    ports:
      - 3333:3333

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    restart: always
    ports:
      - 3000:3000
