services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=bessonorphee@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  # whoami:
  #   image: traefik/whoami
  #   container_name: whoami
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.saas-boilerplate.fr`)"
  #     - "traefik.http.routers.whoami.entrypoints=https"
  #     - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

  backend:
    container_name: backend
    image: ghcr.io/orpheebesson/demo-docker-deploy-backend:production
    restart: always
    env_file:
      - path: ./configurations/backend/.env
    ports:
      - 3333:3333
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.demo-docker-deploy.saas-boilerplate.fr`)"
      - "traefik.http.routers.backend.entrypoints=https"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"

  frontend:
    container_name: frontend
    image: ghcr.io/orpheebesson/demo-docker-deploy-frontend:production
    restart: always
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`demo-docker-deploy.saas-boilerplate.fr`)"
      - "traefik.http.routers.frontend.entrypoints=https"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
